spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:
    url: jdbc:mysql://localhost:3306/book_db
    username: book_user
    password: bookpass
  flyway:
    enabled: true
    location: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operation-sorter: method
    tags-sorter: alpha
    display-request-duration: true

jwt:
  secret: 96c2ebac80a3363a8a5594e095116fc107a8fe7c4c873491cd302f48d30d628e
  access-token-validity: 1800000
  refresh-token-validity: 1209600000